- hosts: npi
  become: yes
  vars:
    app_dir: /opt/light_control
  tasks:
    - name: get code
      git:
        dest: "{{ app_dir }}"
        repo: "https://github.com/DiTsi-Smart-Home/light_control.git"
    - name: template service
      template:
        src: "light_control.service"
        dest: "/etc/systemd/system/"
    - name: enable and restart
      systemd:
        name: light_control
        state: restarted
        daemon_reload: yes
        enabled: yes
      